# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: olegtarasov/get-tag@v2.1
      id: tagName
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine jq

    - name: update setup.py
      run: |
        echo "tag to use $GIT_TAG_NAME"
        sed -i "s/version='.*'/version='$GIT_TAG_NAME'/g" setup.py
    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{secrets.PYPI_TOKEN}}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
